# Change these first
owner: chrislenga # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: The Digital Den Website
    url: $TDD_SITE
  - name: The Digital Den Panel
    url: $TDD_PANEL
  - name: Horoscope Bot
    url: $DISCORD_BOT1_API
    port: $DISCORD_BOT1_PORT
    check: "tcp-ping"
  - name: The Digital Den
    url: $DISCORD_BOT2_API
    port: $DISCORD_BOT2_PORT
    check: "tcp-ping"
  - name: GitHub Bot
    url: $DISCORD_BOT3_API
    port: $DISCORD_BOT3_PORT
    check: "tcp-ping"
  - name: Streamer Bot
    url: $DISCORD_BOT4_API
    port: $DISCORD_BOT4_PORT
    check: "tcp-ping"
  - name: "[FiveM] iSe.GG Combat Remastered"
    url: $ISE1
    port: $ISE2
    check: "tcp-ping"
  - name: "[7D2D] Zed Slayers Anonymous"
    url: $S7D1
    port: $S7D2
    check: "tcp-ping"

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dgden.com
  # baseUrl: /status
  logoUrl: https://dgden.com/images/thedigitalden.svg
  name: The Digital Den Services
  introTitle: "All community services and their statuses."
  introMessage: Find real-time statuses of all services currently used by the community here.
  navbar:
    - title: Main Website
      href: https://dgden.com
    - title: Discord
      href: https://discord.gg/YhvJkuAwYW
    - title: Personal GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: The Digital Den

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
